[package]
name = "main"
version = "0.1.0"
authors = ["Jad K. Haddad <jadkhaddad@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
handler = { path = "../function" }
actix-web = "4.2.1"